---
- name: Check registry credentials and configure authentication if enabled
  block:
    # This task fails if auth is enabled but neither username/password nor a token is provided.
    - name: Check if required registry credentials are provided
      ansible.builtin.fail:
        msg: >
          Registry authentication is enabled (setup_rhaiis_on_rhel_registry_auth_enabled=true)
          but no credentials are provided. Please set either setup_rhaiis_on_rhel_registry_username
          and setup_rhaiis_on_rhel_registry_password, OR setup_rhaiis_on_rhel_registry_auth_token.
      when: >
        (setup_rhaiis_on_rhel_registry_username | default('') == '' or
         setup_rhaiis_on_rhel_registry_password | default('') == '') and
         setup_rhaiis_on_rhel_registry_auth_token | default('') == ''

    - name: Ensure .config/containers directory exists for root user
      ansible.builtin.file:
        path: /root/.config/containers
        state: directory
        mode: '0700'
      become: true

    - name: Ensure .config/containers directory exists for {{ setup_rhaiis_on_rhel_target_user }} user
      ansible.builtin.file:
        path: "{{ '~' + setup_rhaiis_on_rhel_target_user }}/.config/containers"
        state: directory
        mode: '0700'
      become: "{{ setup_rhaiis_on_rhel_target_user != ansible_user_id }}"
      become_user: "{{ setup_rhaiis_on_rhel_target_user }}"

    # Block for username/password authentication method.
    - name: Configure registry authentication using username and password
      block:
        - name: Log in to registry as root using username/password
          containers.podman.podman_login:
            username: "{{ setup_rhaiis_on_rhel_registry_username }}"
            password: "{{ setup_rhaiis_on_rhel_registry_password }}"
            registry: "{{ setup_rhaiis_on_rhel_registry_url }}"
            authfile: /root/.config/containers/auth.json
          become: true

        - name: Log in to registry as {{ setup_rhaiis_on_rhel_target_user }} using username/password
          containers.podman.podman_login:
            username: "{{ setup_rhaiis_on_rhel_registry_username }}"
            password: "{{ setup_rhaiis_on_rhel_registry_password }}"
            registry: "{{ setup_rhaiis_on_rhel_registry_url }}"
            authfile: "{{ '~' + setup_rhaiis_on_rhel_target_user }}/.config/containers/auth.json"
          become: "{{ setup_rhaiis_on_rhel_target_user != ansible_user_id }}"
          become_user: "{{ setup_rhaiis_on_rhel_target_user }}"
      when: >
        setup_rhaiis_on_rhel_registry_username | default('') != '' and
        setup_rhaiis_on_rhel_registry_password | default('') != ''

    # Block for token-based authentication method.
    - name: Configure registry authentication using auth token
      block:
        - name: Create auth.json for root user with token
          ansible.builtin.copy:
            content: |
              {
                "auths": {
                  "{{ setup_rhaiis_on_rhel_registry_url }}": {
                    "auth": "{{ setup_rhaiis_on_rhel_registry_auth_token }}"
                  }
                }
              }
            dest: /root/.config/containers/auth.json
            mode: '0600'
          become: true
          no_log: true

        - name: Create auth.json for {{ setup_rhaiis_on_rhel_target_user }} user with token
          ansible.builtin.copy:
            content: |
              {
                "auths": {
                  "{{ setup_rhaiis_on_rhel_registry_url }}": {
                    "auth": "{{ setup_rhaiis_on_rhel_registry_auth_token }}"
                  }
                }
              }
            dest: "{{ '~' + setup_rhaiis_on_rhel_target_user }}/.config/containers/auth.json"
            mode: '0600'
          become: "{{ setup_rhaiis_on_rhel_target_user != ansible_user_id }}"
          become_user: "{{ setup_rhaiis_on_rhel_target_user }}"
          no_log: true
      when: setup_rhaiis_on_rhel_registry_auth_token | default('') != ''
  when: setup_rhaiis_on_rhel_registry_auth_enabled | default(true)

# This task runs after authentication attempts (if enabled) or directly if auth is not enabled.
- name: Pre-pull container image
  ansible.builtin.command:
    cmd: podman pull {{ setup_rhaiis_on_rhel_vllm_container_image }}
  become: true
  become_user: "{{ setup_rhaiis_on_rhel_target_user }}"
  changed_when: true
