---
- name: Create RHAIIS service file
  ansible.builtin.template:
    src: rhaiis.service.j2
    dest: /etc/systemd/system/rhaiis.service
    mode: '0644'
  become: true
  notify: reload systemd

- name: Enable and start RHAIIS service
  ansible.builtin.systemd:
    name: rhaiis
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Display message about waiting for RHAIIS service
  ansible.builtin.debug:
    msg: "Waiting for RHAIIS service to fully start. This may take several minutes while container images are downloaded..."

- name: Wait for RHAIIS service to respond on the health endpoint
  ansible.builtin.uri:
    url: "http://localhost:{{ setup_rhaiis_on_rhel_vllm_port }}{{ setup_rhaiis_on_rhel_health_endpoint }}"
    method: GET
    return_content: no
    status_code: 200
    timeout: 10
  register: result
  until: result is defined and result.status is defined and result.status == 200
  retries: "{{ setup_rhaiis_on_rhel_health_check_retries | default(20) }}"
  delay: "{{ setup_rhaiis_on_rhel_health_check_delay | default(5) }}"
  ignore_errors: true

- name: Check RHAIIS service status
  ansible.builtin.command:
    cmd: systemctl status rhaiis
  register: service_status
  failed_when: false
  changed_when: false
  become: true

- name: Display RHAIIS service status
  ansible.builtin.debug:
    var: service_status.stdout_lines

- name: Verify RHAIIS container is running
  ansible.builtin.command:
    cmd: podman ps --filter name={{ setup_rhaiis_on_rhel_vllm_container_name }} --format "{{ '{{.Names}}' }}"
  register: container_status
  failed_when: false
  changed_when: false

- name: Fail if RHAIIS service did not start properly
  ansible.builtin.fail:
    msg: "RHAIIS service failed to start properly. Please check the logs using 'journalctl -u rhaiis'."
  when: >
    (result is defined and result.status is not defined or result.status != 200) and
    (container_status.stdout == "" or service_status.rc != 0)
