---
- name: Setup Nvidia CUDA
  hosts: gpu_servers
  gather_facts: true
  become: true

  roles:
    - setup_nvidia_cuda

- name: Deploy model on rhaiis
  hosts: gpu_servers
  become: true
  roles:
    - role: setup_rhaiis_on_rhel
