---
# Default variables for the RHAIIS setup role
setup_rhaiis_on_rhel_hf_token: secret
setup_rhaiis_on_rhel_api_token: secret

# User configuration - automatically detects the SSH user or uses common defaults
# This variable will be set intelligently based on the actual connecting user
# Common users: ec2-user (RHEL/Amazon Linux), ubuntu (Ubuntu), centos (CentOS), cloud-user (some cloud images)
setup_rhaiis_on_rhel_target_user: "{{ ansible_user | default(ansible_user_id | default('ec2-user')) }}"

setup_rhaiis_on_rhel_vllm_cache_dir: "/home/{{ setup_rhaiis_on_rhel_target_user }}/.cache"
setup_rhaiis_on_rhel_vllm_port: 8000
setup_rhaiis_on_rhel_vllm_tensor_parallel_size: 1
setup_rhaiis_on_rhel_vllm_max_model_len: 2048
setup_rhaiis_on_rhel_vllm_model: "RedHatAI/Mistral-7B-Instruct-v0.3-FP8"
setup_rhaiis_on_rhel_vllm_container_name: "rhaiis"
setup_rhaiis_on_rhel_vllm_container_image: "registry.redhat.io/rhaiis/vllm-cuda-rhel9"
setup_rhaiis_on_rhel_mem_overcommit: "1"

# Model pre-download settings
setup_rhaiis_on_rhel_predownload_model: true     # Set to false to skip pre-download
setup_rhaiis_on_rhel_download_timeout: 600       # Download timeout in seconds (10 minutes)
setup_rhaiis_on_rhel_download_retries: 3         # Number of download retry attempts
setup_rhaiis_on_rhel_download_retry_delay: 60    # Delay between retries in seconds
setup_rhaiis_on_rhel_download_async_timeout: 1200 # Ansible async timeout (20 minutes)
setup_rhaiis_on_rhel_download_poll_interval: 30  # Ansible polling interval in seconds

# Registry authentication settings
setup_rhaiis_on_rhel_registry_auth_enabled: true
setup_rhaiis_on_rhel_registry_url: "registry.redhat.io"
setup_rhaiis_on_rhel_registry_username: ""
setup_rhaiis_on_rhel_registry_password: ""
# Alternative: Use a token instead of username/password
setup_rhaiis_on_rhel_registry_auth_token: ""

# Service health check settings
setup_rhaiis_on_rhel_health_check_retries: 30   # Total number of retries (60 x 30s = 30 minutes max wait time)
setup_rhaiis_on_rhel_health_check_delay: 30     # Seconds between retries
setup_rhaiis_on_rhel_health_endpoint: "/docs"  # API endpoint to check
